### ISSUE TITLE
Update example for /v1/redirect-info-about-approval-status-changes

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/TypeApprovalRegister#218]
Example given for /v1/redirect-info-about-approval-status-changes is 

```
example:
                subscriber-application: 'OperationKeyManagement'
                subscriber-release-number: '1.0.0'
                subscriber-operation: '/v1/regard-updated-link'
                subscriber-protocol: 'HTTP'
                subscriber-address:
                  ip-address:
                    ipv-4-address: '1.1.3.7'
                subscriber-port: 3007
```

The service /v1/redirect-info-about-approval-status-changes tends to manage two FC's RegisteringCausesInfoAboutApprovalStatusToRegistryOffice and UpdateOfApprovalStatusCausesInfoToRegistryOffice which are **InvariantProcessSnippet**. These forwardings calls RegistryOffice://v1/regard-updated-approval-status for respective requests. 

I believe providing RegistryOffice in example would be more suitable to this particular scenario. 
Kindly let me know your views. 

```
                subscriber-application: 'RegistryOffice'
                subscriber-release-number: '2.0.1'
                subscriber-operation: '/v1/regard-updated-approval-status'
                subscriber-protocol: 'HTTP'
                subscriber-address:
                  ip-address:
                    ipv-4-address: '1.1.3.8'
                subscriber-port: 3008
```
